### ISSUE TITLE
What is the highest version of SSDT currently supported in the DAXEditor?

### ISSUE THREAD

**Issue by minren118** [DaxEditor/DaxEditor#16]
Unfortunately, the DAXEditor cannot support VS2017. The official website of Microsoft guided me to install the latest SSDT. Could you tell me which version of the highest SSDT the DAXEditor can support now?I would love to use the DAXEditor

**Comment by marcosqlbi** [comment]
You can use DAX Editor in SSDT for Visual Studio 2015.
I'd suggest you to consider Tabular Editor as a more productive tool to edit Tabular models.
https://tabulareditor.github.io/

**Comment by HavenDV** [comment]
> Unfortunately, the DAXEditor cannot support VS2017

Sorry, I'm very busy right now to do this for free. Perhaps in the future



> Could you tell me which version of the highest SSDT the DAXEditor can support now?

![image](https://user-images.githubusercontent.com/3002068/52898498-8604fd80-322a-11e9-8672-a8bdd16c0f04.png)

[16.5](https://go.microsoft.com/fwlink/?LinkID=832313) - Exactly
Rest - not sure
