### ISSUE TITLE
RANKX Syntax issue

### ISSUE THREAD

**Issue by o-o00o-o** [DaxEditor/DaxEditor#5]
Unfortunately I am not able to use DaxEditor at all with my model. 

I get the attached errors. 

It is because the RANKX function allows leaving parameter empty, but DaxEditor (incorrectly) does not allow this.

Marco suggested that the most recent version (30/12) would resolve this but I have updated my version and retried but I get the same issue when I try to Save Measures to BIM file.

[DaxEditorExceptions 2017-01-03.txt](https://github.com/DaxEditor/DaxEditor/files/682387/DaxEditorExceptions.2017-01-03.txt)

**Comment by marcosqlbi** [comment]
It should work now - please confirm!
