### ISSUE TITLE
KPITargetFormatString doesn't always extract the right way

### ISSUE THREAD

**Issue by vstrien** [DaxEditor/DaxEditor#6]
I have a model with the KPI format string `"€" #,0;#,0 -"€";"€" #,0`
When I try to get the measures from this model on my local machine (Windows locale = NL-nl), the format property is read correctly (i.e. the whole format string is put in single quotes) as follows:

```
CALCULATION PROPERTY CURRENCY
    FORMAT = '"€" #,0;#,0 -"€";"€" #,0'
```

However, the `KPITARGETFORMATSTRING` is not written correctly to DAX - it gets double quotes, rendering the expression invalid:
```
    KPITARGETFORMATSTRING = ""€" #,0;#,0 -"€";"€" #,0"
```

The workaround is easy, just replacing the outer double quotes by single ones makes the DAX valid again:
```
    KPITARGETFORMATSTRING = '"€" #,0;#,0 -"€";"€" #,0'
```

**Comment by HavenDV** [comment]
Hello. I made a correction, you can self-assemble dev-branch in the package or wait for the publication of Marco. Thank you!

**Comment by marcosqlbi** [comment]
Thanks Konstantin!
I'll work on a new release next week.

Marco

**Comment by marcosqlbi** [comment]
I just published the new version in Visual Studio Gallery - thanks!
