### ISSUE TITLE
CURRENCY is a valid function name

### ISSUE THREAD

**Issue by marcosqlbi** [DaxEditor/DaxEditor#7]
Calling the function CURRENCY() in a measure raises an exception.
We have to include such a name in the grammar to validate it (if possible - issues in having it as a keyword for the format??)

**Comment by HavenDV** [comment]
Give a simple example, please

**Comment by marcosqlbi** [comment]
You can try this:
CREATE MEASURE Table[test] = 
    CURRENCY ( 1234 );

**Comment by HavenDV** [comment]
Check, please

**Comment by marcosqlbi** [comment]
Released in build 1703.2601
